# Generated by Django 2.2.6 on 2021-02-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('replace_name', models.CharField(max_length=50)),
                ('replace_file', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IFace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=200)),
                ('case_url', models.CharField(max_length=200)),
                ('case_method', models.CharField(max_length=10)),
                ('case_header_id', models.IntegerField()),
                ('case_json', models.CharField(max_length=200)),
                ('case_data', models.CharField(max_length=200)),
                ('case_expected', models.CharField(max_length=200)),
                ('source_address', models.CharField(max_length=50)),
                ('is_able', models.BooleanField()),
                ('suit_id', models.IntegerField()),
                ('result_match_type', models.IntegerField()),
                ('replace_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_id', models.IntegerField()),
                ('ifacec_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('result_response', models.CharField(max_length=200)),
                ('header_id', models.IntegerField()),
                ('request_url', models.CharField(max_length=200)),
                ('request_json', models.CharField(max_length=100)),
                ('request_data', models.CharField(max_length=100)),
                ('result_pass', models.BooleanField()),
                ('request_time', models.FloatField()),
                ('result_des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestSuit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suit_name', models.CharField(max_length=50)),
                ('is_able', models.BooleanField()),
            ],
        ),
    ]
