# Generated by Django 2.2.6 on 2021-02-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0002_headermanager_header_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
