# Generated by Django 2.2.6 on 2021-02-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0003_auto_20210207_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iface',
            name='is_able',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='iface',
            name='result_match_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='header_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='request_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result_pass',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='is_able',
            field=models.BooleanField(null=True),
        ),
    ]
