# Generated by Django 2.2.6 on 2021-02-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0004_auto_20210207_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IFace',
            new_name='ITest',
        ),
    ]
