# Generated by Django 2.2.6 on 2021-02-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0005_auto_20210208_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='ifacec_id',
            new_name='itest_id',
        ),
    ]
