# Generated by Django 2.2.6 on 2021-02-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0006_auto_20210208_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='befortest',
            old_name='replace_file',
            new_name='replace_data',
        ),
        migrations.AddField(
            model_name='befortest',
            name='replace_update_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
