# Generated by Django 2.2.6 on 2021-02-23 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0007_auto_20210208_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='run_counter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='run_ids',
            field=models.CharField(default=datetime.datetime(2021, 2, 23, 10, 38, 44, 264594), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='run_id',
            field=models.IntegerField(null=True),
        ),
    ]
