# Generated by Django 2.2.6 on 2021-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0008_auto_20210223_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='run_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
