# Generated by Django 2.2.6 on 2021-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0009_testrun_run_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='response_status',
            field=models.IntegerField(null=True),
        ),
    ]
