# Generated by Django 2.2.6 on 2021-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0010_testresult_response_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itest',
            name='case_type',
            field=models.IntegerField(null=True),
        ),
    ]
